---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    API_TOKEN: AgAfZqRfnKciKl6cRXcVjg4zVP42ZHRqFqVWpqy/rW1CfSb87McPDQ9OvLItTu48DQMAnPE+IlG7+qlZUJnPe9dZ0TZXNhXTIdGaeIRoF+7aQBUYq1sMzVlrw8xrB3IeKGyzmYtY9AE7tUujtlsWpsvLt4l02M7fendr+F2H1Zi9O4ivnSosR85fDFzTLPrmhcYHA0rNAomikAIHvgDvXziWrvwoz1ay7NAfhN9sZcencKRnz+sIxe+pxedA2bj/XtVQjjzgfJ+EI4vM0DAZ3yHf1HyzXkOeoebERMTpcb7YXM/EoiNoFp/wnSEijoKqN85lfIYPcoZ5csUyuWLFDRXBLS4HNHRsqL5QWWKkCjXRT25nAluG7iEw/D7yh3ISUzlHLfpnZSh8Go2Zcpf83kiC7gD8Zo6uh9F5e5DUO3F24MTBJJccp10z/E4BjyjA4Lgz53OLUatdynEmXAULojJSMUSBgXpU6WKeDZqkZMI/wKSWeMMq59pywBnLXv7ji+TrL/6r3c46FXDE0BTeoNA/bT25bqj7Y5NRfylaMhbsgPqhoYTfNGokg9yZ+CFuw3Bo0vGlmI0Vej+5ivQoWS34Cbfl6WsdbVsPQdRwCqFqPPKoEKhvBraltgpB0NUkwoOL2zWh6h/AOGYp2uXroU4mmZEcKlV7CmM3+Srnu0iOqxaCQchKxpUpSBBW0xIAQ3R4jhSM9pTJ8gfoszdWmo93xgtgKqXLey5vQOXZR+63qcJlyzQk1L0W
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
