---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBBUoZwY6W8A5bRjyoD4hNKE6xY2zGlpPwBKNZXgFWYUxPY6FNVhyywN8FGYRS+O8rQmhuIw8PhsGGkpUmfLWyxzuTe/p3w0mHTQxHxHK8bMpzU8JTrGdAFPTg9+ixkCLf6qRQ8a+L/7r+dk9wGKc1uOnkXhmrdZFaqunul1RExUnznp34gBB74toCNMKtrKR+LAzfXyRRywQr8c0KD+479XO6P+uDjrcvz8bV1s0CIKTV5ig6fm/0fkdAIPwxlQd0fx3BbYEtuz0fj6+DIRhoMmqq6Z/eBQPf41pOOIDEXta0t+jtAhP/XrODxL3lHth7GFy1F0dOwUANXl+gStrDwXtR8Kag4nLlIT4euTltJ3ByPxwLOfYTR9VELwVyjVGI06eZPnzFJ9aXugUGhNu1QFY5Hm/9A9BGDHnShnfg+aKRtTMWiOTtOX0sC8r+pxJsKdevQ08YCnlR5cdI3Ncf3oNr8hnou9Jz/A6MJWhXaHv/JeI7dwOujA0EgllWHm2qoWfdlRApySXQAIzhEYXXnaj/3FxA/WrbqCBuRxNvhVYEY+ZZ88JM6FD5lNTyMp8gxIxXAdJxVnzndQLmTdC9P3reW2DZapNYEo68x1Ak4YzWXsaH6G0tMIUKAVtOtHTogMSCA+kfFOlcM1iA5SOTkGl9TQILw0mMahRu/HJFsVl3XaUEHtzrY/ETk3E+7Ei6399a54099rBztO8T7L7Qw64fQqoijMF0c6hNDuJuYDw9i+QPScjQa
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-token
      namespace: cert-manager
