---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-operator
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        project: mgmt
        path: overlays/mgmt
        suffix: "operator"
      - cluster: prodlab
        project: prod
        suffix: "operator"
        path: overlays/prod
      - cluster: testlab
        project: test
        suffix: "operator"
        path: overlays/test
  template:
    metadata:
      name: "{{project}}-cert-manager-{{suffix}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "-20"
    spec:
      project: "{{project}}"
      ignoreDifferences: []
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - SkipDryRunOnMissingResource=true
      source:
        repoURL: https://github.com/Dayzpd/kustomize-cert-manager
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        name: "{{cluster}}"
        namespace: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager-config
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        project: mgmt
        path: resources/mgmt
        suffix: "config"
      - cluster: prodlab
        project: prod
        path: resources/prod
        suffix: "config"
      - cluster: testlab
        project: test
        path: resources/test
        suffix: "config"
  template:
    metadata:
      name: "{{project}}-cert-manager-{{suffix}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "{{project}}"
      ignoreDifferences: []
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
        syncOptions:
        - ApplyOutOfSyncOnly=true
        - ServerSideApply=true
        - SkipDryRunOnMissingResource=true
      source:
        repoURL: https://github.com/Dayzpd/kustomize-cert-manager
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        name: "{{cluster}}"
        namespace: cert-manager
